/* eslint-disable */
// @ts-nocheck
import { OrderRequest } from "./OrderRequest";
import { deviceColors } from "./deviceColors";
import { deviceImages } from "./deviceImages";

const _legacyOrderRequests: OrderRequest[] = [
  {
    id: "26678",
    devices: [
      {
        name: 'LG 27" UltraFine 5K Monitor',
        image: deviceImages.lgMonitor,
        color: deviceColors.monitor,
        price: "$1,200",
        quantity: 1,
        specs: { display: "27-inch 5K IPS (5120 × 2880)", color: "Silver" },
      },
      {
        name: 'MacBook Pro 16"',
        image: deviceImages.macbook,
        color: deviceColors.macbook,
        price: "$4,200",
        quantity: 2,
        specs: {
          display: "16.2-inch Liquid Retina XDR (3456 × 2234)",
          processor: "M3 Max chip",
          ram: "36GB unified memory",
          storage: "1 TB SSD",
          color: "Space gray",
        },
        addOns: [{ name: "Apple care", price: "$50" }],
      },
      {
        name: "ASUS ProArt StudioBook 16",
        image: deviceImages.asus,
        color: deviceColors.laptop,
        price: "$2,800",
        quantity: 1,
        specs: { display: "16-inch OLED (3840 × 2400)", processor: "Intel Core i9-13980HX", ram: "32GB DDR5", storage: "2 TB SSD", color: "Mineral Black" },
      },
    ],
    service: "Onboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 9, 2025",
    sla: "3-5 working days",
    total: "$12,600",
    recipients: 3,
  },
  {
    id: "26679",
    devices: [
      {
        name: 'Dell UltraSharp 27" Monitor',
        image: deviceImages.dellMonitor,
        color: deviceColors.monitor,
        price: "$80",
        quantity: 1,
        specs: { display: "27-inch 4K IPS (3840 × 2160)", processor: "USB-C Hub", color: "Black" },
      },
      {
        name: "HP EliteBook 840 G9",
        image: deviceImages.hp,
        color: deviceColors.laptop,
        price: "$120",
        quantity: 1,
        specs: { display: "14-inch FHD IPS (1920 × 1080)", processor: "Intel Core i7-1265U", ram: "16GB DDR5", storage: "512 GB SSD", color: "Silver" },
      },
      {
        name: "Logitech MX Master 3S",
        image: deviceImages.logitechMouse,
        color: deviceColors.mouse,
        price: "$50",
        quantity: 1,
        specs: { display: "8K DPI optical sensor", processor: "Bluetooth / USB receiver", color: "Graphite" },
      },
      {
        name: "Sony WH-1000XM5",
        image: deviceImages.sonyHeadphones,
        color: deviceColors.headset,
        price: "$70",
        quantity: 1,
        specs: { display: "30-hour battery life", processor: "Bluetooth 5.2 / 3.5mm", color: "Black" },
      },
    ],
    service: "Offboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 16, 2025",
    sla: "5-7 working days",
    total: "$320",
    recipients: 2,
    pickupDate: "Jan 18, 2025",
  },
  {
    id: "26676",
    devices: [
      {
        name: 'MacBook Pro 14"',
        image: deviceImages.macbook,
        color: deviceColors.macbook,
        price: "$150",
        quantity: 1,
        specs: {
          display: "14.2-inch Liquid Retina XDR (3024 × 1964)",
          processor: "M3 Pro chip",
          ram: "18GB unified memory",
          storage: "512 GB SSD",
          color: "Space Black",
        },
      },
      {
        name: "Sony WH-1000XM5",
        image: deviceImages.sonyHeadphones,
        color: deviceColors.headset,
        price: "$50",
        quantity: 1,
        specs: { display: "30-hour battery life", processor: "Bluetooth 5.2 / 3.5mm", color: "Silver" },
      },
    ],
    service: "Storage",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 16, 2025",
    sla: "1-2 working days",
    total: "$200",
    recipients: 1,
    storageDuration: "3 months",
  },
  {
    id: "26675",
    devices: [
      {
        name: "Dell XPS 15",
        image: deviceImages.dell,
        color: deviceColors.laptop,
        price: "$1,799",
        quantity: 3,
        specs: { display: "15.6-inch OLED (3456 × 2160)", processor: "Intel Core i7-13700H", ram: "32GB DDR5", storage: "1 TB SSD", color: "Platinum Silver" },
      },
      {
        name: 'Samsung 32" 4K Monitor',
        image: deviceImages.samsungMonitor,
        color: deviceColors.monitor,
        price: "$450",
        quantity: 3,
        specs: { display: "32-inch 4K VA (3840 × 2160)", color: "Black" },
      },
    ],
    service: "Onboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 20, 2025",
    sla: "3-5 working days",
    total: "$6,747",
    recipients: 3,
  },
  {
    id: "26674",
    devices: [
      {
        name: "Lenovo ThinkPad X1",
        image: deviceImages.lenovo,
        color: deviceColors.laptop,
        price: "$1,649",
        quantity: 2,
        specs: { display: "14-inch 2.8K OLED (2880 × 1800)", processor: "Intel Core i7-1365U", ram: "16GB LPDDR5", storage: "512 GB SSD", color: "Black" },
      },
      {
        name: "Jabra Evolve2 85",
        image: deviceImages.jabraHeadphones,
        color: deviceColors.headset,
        price: "$449",
        quantity: 2,
        specs: { display: "37-hour battery life", processor: "Bluetooth 5.1 / USB-C", color: "Black" },
      },
    ],
    service: "Onboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 22, 2025",
    sla: "3-5 working days",
    total: "$4,196",
    recipients: 2,
  },
  {
    id: "26673",
    devices: [
      {
        name: 'iPad Pro 12.9"',
        image: deviceImages.ipad,
        color: deviceColors.ipad,
        price: "$1,099",
        quantity: 5,
        specs: { display: "12.9-inch Liquid Retina XDR", processor: "M2 chip", storage: "256 GB", color: "Space Gray" },
      },
    ],
    service: "Onboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 25, 2025",
    sla: "3-5 working days",
    total: "$5,495",
    recipients: 5,
  },
  {
    id: "26672",
    devices: [
      {
        name: "HP EliteBook 840 G9",
        image: deviceImages.hp,
        color: deviceColors.laptop,
        price: "$120",
        quantity: 1,
        specs: { display: "14-inch FHD IPS", processor: "Intel Core i5-1245U", ram: "16GB DDR5", storage: "256 GB SSD", color: "Silver" },
      },
      { name: "Logitech MX Master 3S", image: deviceImages.logitechMouse, color: deviceColors.mouse, price: "$50", quantity: 1 },
    ],
    service: "Offboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 18, 2025",
    sla: "5-7 working days",
    total: "$170",
    recipients: 1,
    pickupDate: "Jan 20, 2025",
  },
  {
    id: "26671",
    devices: [
      {
        name: 'MacBook Pro 16"',
        image: deviceImages.macbook,
        color: deviceColors.macbook,
        price: "$3,499",
        quantity: 4,
        specs: { display: "16.2-inch Liquid Retina XDR", processor: "M3 Max chip", ram: "36GB unified memory", storage: "1 TB SSD", color: "Space Black" },
      },
      { name: 'LG 27" UltraFine 5K Monitor', image: deviceImages.lgMonitor, color: deviceColors.monitor, price: "$1,299", quantity: 4 },
      { name: "AirPods Pro", image: deviceImages.airpodsPro, color: deviceColors.airpods, price: "$249", quantity: 4 },
    ],
    service: "Onboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Feb 1, 2025",
    sla: "3-5 working days",
    total: "$20,188",
    recipients: 4,
  },
  {
    id: "26670",
    devices: [
      {
        name: "ASUS ProArt StudioBook 16",
        image: deviceImages.asus,
        color: deviceColors.laptop,
        price: "$200",
        quantity: 2,
        specs: { display: "16-inch 4K OLED", processor: "Intel Core i9-13980HX", ram: "64GB DDR5", storage: "2 TB SSD", color: "Mineral Black" },
      },
    ],
    service: "Storage",
    amount: "$150.00",
    country: "United States",
    dueDate: "Jan 28, 2025",
    sla: "1-2 working days",
    total: "$400",
    recipients: 2,
    storageDuration: "6 months",
  },
  {
    id: "26669",
    devices: [
      {
        name: 'Dell UltraSharp 27" Monitor',
        image: deviceImages.dellMonitor,
        color: deviceColors.monitor,
        price: "$899",
        quantity: 6,
        specs: { display: "27-inch 4K IPS", color: "Black" },
      },
      { name: "Microsoft Arc Mouse", image: deviceImages.microsoftMouse, color: deviceColors.mouse, price: "$79", quantity: 6 },
    ],
    service: "Onboarding",
    amount: "$150.00",
    country: "United States",
    dueDate: "Feb 5, 2025",
    sla: "3-5 working days",
    total: "$5,868",
    recipients: 6,
  },
];
export { _legacyOrderRequests };
