/* eslint-disable */
// @ts-nocheck
const employees = [
  {
    id: "1",
    initials: "OR",
    name: "Olivia Rhye",
    email: "olivia@rayda.co",
    role: "Manager",
    address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
    amount: "$10,347.78",
    status: "verification-pending" as const,
    signature: "required" as const,
  },
  {
    id: "2",
    initials: "PB",
    name: "Phoenix Baker",
    email: "phoenix@rayda.co",
    role: "Team Lead",
    address: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
    amount: "$5,282.80",
    status: "verification-pending" as const,
    signature: "required" as const,
  },
  {
    id: "3",
    initials: "LS",
    name: "Lana Steiner",
    email: "lana@rayda.co",
    role: "Entry-Level",
    address: "8502 Preston Rd. Inglewood, Maine 98380",
    amount: "$3,069.37",
    status: "verification-pending" as const,
    signature: "required" as const,
  },
  {
    id: "4",
    initials: "DW",
    name: "Demi Wilkinson",
    email: "demi@rayda.co",
    role: "Middle Management",
    address: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    amount: "$8,073.94",
    status: "completed" as const,
    signature: "not-required" as const,
  },
  {
    id: "5",
    initials: "CW",
    name: "Candice Wu",
    email: "candice@rayda.co",
    role: "Specialist",
    address: "4140 Parker Rd. Allentown, New Mexico 31008",
    amount: "$121.35",
    status: "completed" as const,
    signature: "not-required" as const,
  },
  {
    id: "6",
    initials: "NC",
    name: "Natali Craig",
    email: "natali@rayda.co",
    role: "Senior Management",
    address: "2464 Royal Ln. Mesa, New Jersey 45463",
    amount: "$20,563.22",
    status: "completed" as const,
    signature: "not-required" as const,
  },
];
export { employees };
