/* eslint-disable */
// @ts-nocheck
const initialActivityFeed = [
  {
    id: "a1",
    type: "system",
    initials: "R",
    title: "Confirmation email sent",
    time: "11:50pm · 15 July 2025",
    description: "Delivery preferences confirmed, saved and sent to",
    highlight: "Sarah Chen",
  },
  {
    id: "a2",
    type: "user",
    initials: "SC",
    title: "Signature requirement set",
    time: "11:50pm · 15 July 2025",
    description: "Sarah Chen enabled signature requirement for sub-order",
    highlight: "#003",
    badge: { label: "Signature required", style: "bg-[#e7f0ff] text-[#0948b5] ring-[#8fb9ff]" },
  },
  {
    id: "a3",
    type: "user",
    initials: "SC",
    title: "Delivery information verified",
    time: "11:50pm · 15 July 2025",
    description: "Sarah Chen confirmed the address, phone, delivery notes, and signature requirement",
    highlight: null,
    badge: { label: "Not required", style: "bg-[#fafafa] text-[#414651] ring-[#e9eaeb]" },
  },
  {
    id: "a4",
    type: "system",
    initials: "R",
    title: "Verification email sent",
    time: "11:50pm · 15 July 2025",
    description: "A secure link was sent to",
    highlight: "Sarah Chen",
    description2: "to verify delivery information before the order ships.",
  },
  {
    id: "a5",
    type: "product",
    initials: "HP",
    title: "HP ProBook 440 G10 — 4GB Intel Core i7",
    time: "4:05am · 18 December 2025",
    action: "Set signature requirement: Required · Comment from",
    highlight: "Rayda",
    message: "Item out of stock. We're restocking soon and will notify you!",
  },
  {
    id: "a6",
    type: "product",
    initials: "HP",
    title: "HP ProBook 440 G10 — 4GB Intel Core i7",
    time: "2:20pm · 30 August 2025",
    action: "Document has been uploaded for equipment",
    highlight: null,
    attachment: { name: "Hashcode.zip", size: "720 KB" },
  },
  {
    id: "a7",
    type: "product",
    initials: "HP",
    title: "HP ProBook 440 G10 — 4GB Intel Core i7",
    time: "9:45am · 22 July 2025",
    action: "Serial number has been updated to",
    highlight: "C02FJ9D3H5G7",
  },
  {
    id: "a8",
    type: "product",
    initials: "HP",
    title: "HP ProBook 440 G10 — 4GB Intel Core i7",
    time: "11:50pm · 15 July 2025",
    action: "Item delivered! Use the tracking link in your email or contact support if needed.",
    badge: { label: "Delivered", style: "bg-[#ecfdf3] text-[#067647] ring-[#abefc6]" },
  },
  {
    id: "a9",
    type: "product",
    initials: "HP",
    title: "HP ProBook 440 G10 — 4GB Intel Core i7",
    time: "8:00am · 1 July 2025",
    action: "Order in transit. Check your email for tracking updates.",
    badge: { label: "In transit", style: "bg-[#fffaeb] text-[#b54708] ring-[#fedf89]" },
  },
  {
    id: "a10",
    type: "person",
    initials: "BP",
    title: "Foresight (Brian Paul)",
    time: "3:30pm · 12 April 2025",
    action: "Placed an order",
    highlight: "ORD-1007",
    isLast: true,
  },
];
export { initialActivityFeed };
